apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-api-dev
  namespace: argocd
  labels:
    app: dotnet-api
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/betuanminh22032003/labArgoCD02.git
    targetRevision: develop              # Track develop branch
    path: helm/dotnet-api
    
    helm:
      releaseName: dotnet-api
      valueFiles:
        - values.yaml
        - values-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m