apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-api-prod
  namespace: argocd
  labels:
    app: dotnet-api
    env: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production                    # Use restricted project
  
  source:
    repoURL: https://github.com/betuanminh22032003/labArgoCD02.git
    targetRevision: v1.0.0               # Pin to specific tag
    path: helm/dotnet-api
    
    helm:
      releaseName: dotnet-api
      valueFiles:
        - values.yaml
        - values-prod.yaml
      values: |
        image:
          tag: "v1.0.0"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  # NO automated sync for production!
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true