apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-declarative
  namespace: argocd
  # Optional: Add finalizer to cascade delete
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/betuanminh22032003/labArgoCD02.git
    targetRevision: HEAD
    path: manifests/simple-nginx
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-declarative
  
  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true       # Delete resources when removed from Git
      selfHeal: true    # Revert manual cluster changes
      allowEmpty: false # Don't sync empty directories
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m